name: dub
version: 0.0.3
description: Unofficial Dub.co SDK
homepage: https://dub.co
repository: https://github.com/thealphamerc/dub-dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  dio: "^5.2.0"
  json_annotation: "^4.4.0"

dev_dependencies:
  build_runner: any
  json_serializable: "^6.1.5"
  test: ^1.16.0
