// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_city_analytics200_response_inner.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

GetCityAnalytics200ResponseInner _$GetCityAnalytics200ResponseInnerFromJson(
        Map<String, dynamic> json) =>
    $checkedCreate(
      'GetCityAnalytics200ResponseInner',
      json,
      ($checkedConvert) {
        $checkKeys(
          json,
          requiredKeys: const ['city', 'country', 'clicks'],
        );
        final val = GetCityAnalytics200ResponseInner(
          city: $checkedConvert('city', (v) => v as String),
          country: $checkedConvert(
              'country',
              (v) => $enumDecode(
                  _$GetCityAnalytics200ResponseInnerCountryEnumEnumMap, v)),
          clicks: $checkedConvert('clicks', (v) => v as num),
        );
        return val;
      },
    );

Map<String, dynamic> _$GetCityAnalytics200ResponseInnerToJson(
        GetCityAnalytics200ResponseInner instance) =>
    <String, dynamic>{
      'city': instance.city,
      'country': _$GetCityAnalytics200ResponseInnerCountryEnumEnumMap[
          instance.country]!,
      'clicks': instance.clicks,
    };

const _$GetCityAnalytics200ResponseInnerCountryEnumEnumMap = {
  GetCityAnalytics200ResponseInnerCountryEnum.AF: 'AF',
  GetCityAnalytics200ResponseInnerCountryEnum.AL: 'AL',
  GetCityAnalytics200ResponseInnerCountryEnum.DZ: 'DZ',
  GetCityAnalytics200ResponseInnerCountryEnum.AS: 'AS',
  GetCityAnalytics200ResponseInnerCountryEnum.AD: 'AD',
  GetCityAnalytics200ResponseInnerCountryEnum.AO: 'AO',
  GetCityAnalytics200ResponseInnerCountryEnum.AI: 'AI',
  GetCityAnalytics200ResponseInnerCountryEnum.AQ: 'AQ',
  GetCityAnalytics200ResponseInnerCountryEnum.AG: 'AG',
  GetCityAnalytics200ResponseInnerCountryEnum.AR: 'AR',
  GetCityAnalytics200ResponseInnerCountryEnum.AM: 'AM',
  GetCityAnalytics200ResponseInnerCountryEnum.AW: 'AW',
  GetCityAnalytics200ResponseInnerCountryEnum.AU: 'AU',
  GetCityAnalytics200ResponseInnerCountryEnum.AT: 'AT',
  GetCityAnalytics200ResponseInnerCountryEnum.AZ: 'AZ',
  GetCityAnalytics200ResponseInnerCountryEnum.BS: 'BS',
  GetCityAnalytics200ResponseInnerCountryEnum.BH: 'BH',
  GetCityAnalytics200ResponseInnerCountryEnum.BD: 'BD',
  GetCityAnalytics200ResponseInnerCountryEnum.BB: 'BB',
  GetCityAnalytics200ResponseInnerCountryEnum.BY: 'BY',
  GetCityAnalytics200ResponseInnerCountryEnum.BE: 'BE',
  GetCityAnalytics200ResponseInnerCountryEnum.BZ: 'BZ',
  GetCityAnalytics200ResponseInnerCountryEnum.BJ: 'BJ',
  GetCityAnalytics200ResponseInnerCountryEnum.BM: 'BM',
  GetCityAnalytics200ResponseInnerCountryEnum.BT: 'BT',
  GetCityAnalytics200ResponseInnerCountryEnum.BO: 'BO',
  GetCityAnalytics200ResponseInnerCountryEnum.BA: 'BA',
  GetCityAnalytics200ResponseInnerCountryEnum.BW: 'BW',
  GetCityAnalytics200ResponseInnerCountryEnum.BV: 'BV',
  GetCityAnalytics200ResponseInnerCountryEnum.BR: 'BR',
  GetCityAnalytics200ResponseInnerCountryEnum.IO: 'IO',
  GetCityAnalytics200ResponseInnerCountryEnum.BN: 'BN',
  GetCityAnalytics200ResponseInnerCountryEnum.BG: 'BG',
  GetCityAnalytics200ResponseInnerCountryEnum.BF: 'BF',
  GetCityAnalytics200ResponseInnerCountryEnum.BI: 'BI',
  GetCityAnalytics200ResponseInnerCountryEnum.KH: 'KH',
  GetCityAnalytics200ResponseInnerCountryEnum.CM: 'CM',
  GetCityAnalytics200ResponseInnerCountryEnum.CA: 'CA',
  GetCityAnalytics200ResponseInnerCountryEnum.CV: 'CV',
  GetCityAnalytics200ResponseInnerCountryEnum.KY: 'KY',
  GetCityAnalytics200ResponseInnerCountryEnum.CF: 'CF',
  GetCityAnalytics200ResponseInnerCountryEnum.TD: 'TD',
  GetCityAnalytics200ResponseInnerCountryEnum.CL: 'CL',
  GetCityAnalytics200ResponseInnerCountryEnum.CN: 'CN',
  GetCityAnalytics200ResponseInnerCountryEnum.CX: 'CX',
  GetCityAnalytics200ResponseInnerCountryEnum.CC: 'CC',
  GetCityAnalytics200ResponseInnerCountryEnum.CO: 'CO',
  GetCityAnalytics200ResponseInnerCountryEnum.KM: 'KM',
  GetCityAnalytics200ResponseInnerCountryEnum.CG: 'CG',
  GetCityAnalytics200ResponseInnerCountryEnum.CD: 'CD',
  GetCityAnalytics200ResponseInnerCountryEnum.CK: 'CK',
  GetCityAnalytics200ResponseInnerCountryEnum.CR: 'CR',
  GetCityAnalytics200ResponseInnerCountryEnum.CI: 'CI',
  GetCityAnalytics200ResponseInnerCountryEnum.HR: 'HR',
  GetCityAnalytics200ResponseInnerCountryEnum.CU: 'CU',
  GetCityAnalytics200ResponseInnerCountryEnum.CY: 'CY',
  GetCityAnalytics200ResponseInnerCountryEnum.CZ: 'CZ',
  GetCityAnalytics200ResponseInnerCountryEnum.DK: 'DK',
  GetCityAnalytics200ResponseInnerCountryEnum.DJ: 'DJ',
  GetCityAnalytics200ResponseInnerCountryEnum.DM: 'DM',
  GetCityAnalytics200ResponseInnerCountryEnum.DO: 'DO',
  GetCityAnalytics200ResponseInnerCountryEnum.EC: 'EC',
  GetCityAnalytics200ResponseInnerCountryEnum.EG: 'EG',
  GetCityAnalytics200ResponseInnerCountryEnum.SV: 'SV',
  GetCityAnalytics200ResponseInnerCountryEnum.GQ: 'GQ',
  GetCityAnalytics200ResponseInnerCountryEnum.ER: 'ER',
  GetCityAnalytics200ResponseInnerCountryEnum.EE: 'EE',
  GetCityAnalytics200ResponseInnerCountryEnum.ET: 'ET',
  GetCityAnalytics200ResponseInnerCountryEnum.FK: 'FK',
  GetCityAnalytics200ResponseInnerCountryEnum.FO: 'FO',
  GetCityAnalytics200ResponseInnerCountryEnum.FJ: 'FJ',
  GetCityAnalytics200ResponseInnerCountryEnum.FI: 'FI',
  GetCityAnalytics200ResponseInnerCountryEnum.FR: 'FR',
  GetCityAnalytics200ResponseInnerCountryEnum.GF: 'GF',
  GetCityAnalytics200ResponseInnerCountryEnum.PF: 'PF',
  GetCityAnalytics200ResponseInnerCountryEnum.TF: 'TF',
  GetCityAnalytics200ResponseInnerCountryEnum.GA: 'GA',
  GetCityAnalytics200ResponseInnerCountryEnum.GM: 'GM',
  GetCityAnalytics200ResponseInnerCountryEnum.GE: 'GE',
  GetCityAnalytics200ResponseInnerCountryEnum.DE: 'DE',
  GetCityAnalytics200ResponseInnerCountryEnum.GH: 'GH',
  GetCityAnalytics200ResponseInnerCountryEnum.GI: 'GI',
  GetCityAnalytics200ResponseInnerCountryEnum.GR: 'GR',
  GetCityAnalytics200ResponseInnerCountryEnum.GL: 'GL',
  GetCityAnalytics200ResponseInnerCountryEnum.GD: 'GD',
  GetCityAnalytics200ResponseInnerCountryEnum.GP: 'GP',
  GetCityAnalytics200ResponseInnerCountryEnum.GU: 'GU',
  GetCityAnalytics200ResponseInnerCountryEnum.GT: 'GT',
  GetCityAnalytics200ResponseInnerCountryEnum.GN: 'GN',
  GetCityAnalytics200ResponseInnerCountryEnum.GW: 'GW',
  GetCityAnalytics200ResponseInnerCountryEnum.GY: 'GY',
  GetCityAnalytics200ResponseInnerCountryEnum.HT: 'HT',
  GetCityAnalytics200ResponseInnerCountryEnum.HM: 'HM',
  GetCityAnalytics200ResponseInnerCountryEnum.VA: 'VA',
  GetCityAnalytics200ResponseInnerCountryEnum.HN: 'HN',
  GetCityAnalytics200ResponseInnerCountryEnum.HK: 'HK',
  GetCityAnalytics200ResponseInnerCountryEnum.HU: 'HU',
  GetCityAnalytics200ResponseInnerCountryEnum.IS: 'IS',
  GetCityAnalytics200ResponseInnerCountryEnum.IN: 'IN',
  GetCityAnalytics200ResponseInnerCountryEnum.ID: 'ID',
  GetCityAnalytics200ResponseInnerCountryEnum.IR: 'IR',
  GetCityAnalytics200ResponseInnerCountryEnum.IQ: 'IQ',
  GetCityAnalytics200ResponseInnerCountryEnum.IE: 'IE',
  GetCityAnalytics200ResponseInnerCountryEnum.IL: 'IL',
  GetCityAnalytics200ResponseInnerCountryEnum.IT: 'IT',
  GetCityAnalytics200ResponseInnerCountryEnum.JM: 'JM',
  GetCityAnalytics200ResponseInnerCountryEnum.JP: 'JP',
  GetCityAnalytics200ResponseInnerCountryEnum.JO: 'JO',
  GetCityAnalytics200ResponseInnerCountryEnum.KZ: 'KZ',
  GetCityAnalytics200ResponseInnerCountryEnum.KE: 'KE',
  GetCityAnalytics200ResponseInnerCountryEnum.KI: 'KI',
  GetCityAnalytics200ResponseInnerCountryEnum.KP: 'KP',
  GetCityAnalytics200ResponseInnerCountryEnum.KR: 'KR',
  GetCityAnalytics200ResponseInnerCountryEnum.KW: 'KW',
  GetCityAnalytics200ResponseInnerCountryEnum.KG: 'KG',
  GetCityAnalytics200ResponseInnerCountryEnum.LA: 'LA',
  GetCityAnalytics200ResponseInnerCountryEnum.LV: 'LV',
  GetCityAnalytics200ResponseInnerCountryEnum.LB: 'LB',
  GetCityAnalytics200ResponseInnerCountryEnum.LS: 'LS',
  GetCityAnalytics200ResponseInnerCountryEnum.LR: 'LR',
  GetCityAnalytics200ResponseInnerCountryEnum.LY: 'LY',
  GetCityAnalytics200ResponseInnerCountryEnum.LI: 'LI',
  GetCityAnalytics200ResponseInnerCountryEnum.LT: 'LT',
  GetCityAnalytics200ResponseInnerCountryEnum.LU: 'LU',
  GetCityAnalytics200ResponseInnerCountryEnum.MO: 'MO',
  GetCityAnalytics200ResponseInnerCountryEnum.MG: 'MG',
  GetCityAnalytics200ResponseInnerCountryEnum.MW: 'MW',
  GetCityAnalytics200ResponseInnerCountryEnum.MY: 'MY',
  GetCityAnalytics200ResponseInnerCountryEnum.MV: 'MV',
  GetCityAnalytics200ResponseInnerCountryEnum.ML: 'ML',
  GetCityAnalytics200ResponseInnerCountryEnum.MT: 'MT',
  GetCityAnalytics200ResponseInnerCountryEnum.MH: 'MH',
  GetCityAnalytics200ResponseInnerCountryEnum.MQ: 'MQ',
  GetCityAnalytics200ResponseInnerCountryEnum.MR: 'MR',
  GetCityAnalytics200ResponseInnerCountryEnum.MU: 'MU',
  GetCityAnalytics200ResponseInnerCountryEnum.YT: 'YT',
  GetCityAnalytics200ResponseInnerCountryEnum.MX: 'MX',
  GetCityAnalytics200ResponseInnerCountryEnum.FM: 'FM',
  GetCityAnalytics200ResponseInnerCountryEnum.MD: 'MD',
  GetCityAnalytics200ResponseInnerCountryEnum.MC: 'MC',
  GetCityAnalytics200ResponseInnerCountryEnum.MN: 'MN',
  GetCityAnalytics200ResponseInnerCountryEnum.MS: 'MS',
  GetCityAnalytics200ResponseInnerCountryEnum.MA: 'MA',
  GetCityAnalytics200ResponseInnerCountryEnum.MZ: 'MZ',
  GetCityAnalytics200ResponseInnerCountryEnum.MM: 'MM',
  GetCityAnalytics200ResponseInnerCountryEnum.NA: 'NA',
  GetCityAnalytics200ResponseInnerCountryEnum.NR: 'NR',
  GetCityAnalytics200ResponseInnerCountryEnum.NP: 'NP',
  GetCityAnalytics200ResponseInnerCountryEnum.NL: 'NL',
  GetCityAnalytics200ResponseInnerCountryEnum.NC: 'NC',
  GetCityAnalytics200ResponseInnerCountryEnum.NZ: 'NZ',
  GetCityAnalytics200ResponseInnerCountryEnum.NI: 'NI',
  GetCityAnalytics200ResponseInnerCountryEnum.NE: 'NE',
  GetCityAnalytics200ResponseInnerCountryEnum.NG: 'NG',
  GetCityAnalytics200ResponseInnerCountryEnum.NU: 'NU',
  GetCityAnalytics200ResponseInnerCountryEnum.NF: 'NF',
  GetCityAnalytics200ResponseInnerCountryEnum.MK: 'MK',
  GetCityAnalytics200ResponseInnerCountryEnum.MP: 'MP',
  GetCityAnalytics200ResponseInnerCountryEnum.NO: 'NO',
  GetCityAnalytics200ResponseInnerCountryEnum.OM: 'OM',
  GetCityAnalytics200ResponseInnerCountryEnum.PK: 'PK',
  GetCityAnalytics200ResponseInnerCountryEnum.PW: 'PW',
  GetCityAnalytics200ResponseInnerCountryEnum.PS: 'PS',
  GetCityAnalytics200ResponseInnerCountryEnum.PA: 'PA',
  GetCityAnalytics200ResponseInnerCountryEnum.PG: 'PG',
  GetCityAnalytics200ResponseInnerCountryEnum.PY: 'PY',
  GetCityAnalytics200ResponseInnerCountryEnum.PE: 'PE',
  GetCityAnalytics200ResponseInnerCountryEnum.PH: 'PH',
  GetCityAnalytics200ResponseInnerCountryEnum.PN: 'PN',
  GetCityAnalytics200ResponseInnerCountryEnum.PL: 'PL',
  GetCityAnalytics200ResponseInnerCountryEnum.PT: 'PT',
  GetCityAnalytics200ResponseInnerCountryEnum.PR: 'PR',
  GetCityAnalytics200ResponseInnerCountryEnum.QA: 'QA',
  GetCityAnalytics200ResponseInnerCountryEnum.RE: 'RE',
  GetCityAnalytics200ResponseInnerCountryEnum.RO: 'RO',
  GetCityAnalytics200ResponseInnerCountryEnum.RU: 'RU',
  GetCityAnalytics200ResponseInnerCountryEnum.RW: 'RW',
  GetCityAnalytics200ResponseInnerCountryEnum.SH: 'SH',
  GetCityAnalytics200ResponseInnerCountryEnum.KN: 'KN',
  GetCityAnalytics200ResponseInnerCountryEnum.LC: 'LC',
  GetCityAnalytics200ResponseInnerCountryEnum.PM: 'PM',
  GetCityAnalytics200ResponseInnerCountryEnum.VC: 'VC',
  GetCityAnalytics200ResponseInnerCountryEnum.WS: 'WS',
  GetCityAnalytics200ResponseInnerCountryEnum.SM: 'SM',
  GetCityAnalytics200ResponseInnerCountryEnum.ST: 'ST',
  GetCityAnalytics200ResponseInnerCountryEnum.SA: 'SA',
  GetCityAnalytics200ResponseInnerCountryEnum.SN: 'SN',
  GetCityAnalytics200ResponseInnerCountryEnum.SC: 'SC',
  GetCityAnalytics200ResponseInnerCountryEnum.SL: 'SL',
  GetCityAnalytics200ResponseInnerCountryEnum.SG: 'SG',
  GetCityAnalytics200ResponseInnerCountryEnum.SK: 'SK',
  GetCityAnalytics200ResponseInnerCountryEnum.SI: 'SI',
  GetCityAnalytics200ResponseInnerCountryEnum.SB: 'SB',
  GetCityAnalytics200ResponseInnerCountryEnum.SO: 'SO',
  GetCityAnalytics200ResponseInnerCountryEnum.ZA: 'ZA',
  GetCityAnalytics200ResponseInnerCountryEnum.GS: 'GS',
  GetCityAnalytics200ResponseInnerCountryEnum.ES: 'ES',
  GetCityAnalytics200ResponseInnerCountryEnum.LK: 'LK',
  GetCityAnalytics200ResponseInnerCountryEnum.SD: 'SD',
  GetCityAnalytics200ResponseInnerCountryEnum.SR: 'SR',
  GetCityAnalytics200ResponseInnerCountryEnum.SJ: 'SJ',
  GetCityAnalytics200ResponseInnerCountryEnum.SZ: 'SZ',
  GetCityAnalytics200ResponseInnerCountryEnum.SE: 'SE',
  GetCityAnalytics200ResponseInnerCountryEnum.CH: 'CH',
  GetCityAnalytics200ResponseInnerCountryEnum.SY: 'SY',
  GetCityAnalytics200ResponseInnerCountryEnum.TW: 'TW',
  GetCityAnalytics200ResponseInnerCountryEnum.TJ: 'TJ',
  GetCityAnalytics200ResponseInnerCountryEnum.TZ: 'TZ',
  GetCityAnalytics200ResponseInnerCountryEnum.TH: 'TH',
  GetCityAnalytics200ResponseInnerCountryEnum.TL: 'TL',
  GetCityAnalytics200ResponseInnerCountryEnum.TG: 'TG',
  GetCityAnalytics200ResponseInnerCountryEnum.TK: 'TK',
  GetCityAnalytics200ResponseInnerCountryEnum.TO: 'TO',
  GetCityAnalytics200ResponseInnerCountryEnum.TT: 'TT',
  GetCityAnalytics200ResponseInnerCountryEnum.TN: 'TN',
  GetCityAnalytics200ResponseInnerCountryEnum.TR: 'TR',
  GetCityAnalytics200ResponseInnerCountryEnum.TM: 'TM',
  GetCityAnalytics200ResponseInnerCountryEnum.TC: 'TC',
  GetCityAnalytics200ResponseInnerCountryEnum.TV: 'TV',
  GetCityAnalytics200ResponseInnerCountryEnum.UG: 'UG',
  GetCityAnalytics200ResponseInnerCountryEnum.UA: 'UA',
  GetCityAnalytics200ResponseInnerCountryEnum.AE: 'AE',
  GetCityAnalytics200ResponseInnerCountryEnum.GB: 'GB',
  GetCityAnalytics200ResponseInnerCountryEnum.US: 'US',
  GetCityAnalytics200ResponseInnerCountryEnum.UM: 'UM',
  GetCityAnalytics200ResponseInnerCountryEnum.UY: 'UY',
  GetCityAnalytics200ResponseInnerCountryEnum.UZ: 'UZ',
  GetCityAnalytics200ResponseInnerCountryEnum.VU: 'VU',
  GetCityAnalytics200ResponseInnerCountryEnum.VE: 'VE',
  GetCityAnalytics200ResponseInnerCountryEnum.VN: 'VN',
  GetCityAnalytics200ResponseInnerCountryEnum.VG: 'VG',
  GetCityAnalytics200ResponseInnerCountryEnum.VI: 'VI',
  GetCityAnalytics200ResponseInnerCountryEnum.WF: 'WF',
  GetCityAnalytics200ResponseInnerCountryEnum.EH: 'EH',
  GetCityAnalytics200ResponseInnerCountryEnum.YE: 'YE',
  GetCityAnalytics200ResponseInnerCountryEnum.ZM: 'ZM',
  GetCityAnalytics200ResponseInnerCountryEnum.ZW: 'ZW',
  GetCityAnalytics200ResponseInnerCountryEnum.AX: 'AX',
  GetCityAnalytics200ResponseInnerCountryEnum.BQ: 'BQ',
  GetCityAnalytics200ResponseInnerCountryEnum.CW: 'CW',
  GetCityAnalytics200ResponseInnerCountryEnum.GG: 'GG',
  GetCityAnalytics200ResponseInnerCountryEnum.IM: 'IM',
  GetCityAnalytics200ResponseInnerCountryEnum.JE: 'JE',
  GetCityAnalytics200ResponseInnerCountryEnum.ME: 'ME',
  GetCityAnalytics200ResponseInnerCountryEnum.BL: 'BL',
  GetCityAnalytics200ResponseInnerCountryEnum.MF: 'MF',
  GetCityAnalytics200ResponseInnerCountryEnum.RS: 'RS',
  GetCityAnalytics200ResponseInnerCountryEnum.SX: 'SX',
  GetCityAnalytics200ResponseInnerCountryEnum.SS: 'SS',
  GetCityAnalytics200ResponseInnerCountryEnum.XK: 'XK',
  GetCityAnalytics200ResponseInnerCountryEnum.unknownDefaultOpenApi:
      'unknown_default_open_api',
};
